### PR TITLE
Rename calender to calendar and add HTML redirects

### PR DESCRIPTION
**Pull request by pbock**
The URL for the calendar page is currently _calend**a**r.html_ in the English version but _calend**e**r.html_ in the German version. This renames _calender_ to the conventional spelling of _calendar_.

Because [cool URIs don't change](http://www.w3.org/Provider/Style/URI.html), we need to redirect the old URI. GitHub pages [recommends doing this with the `jekyll-redirect-from` gem](https://github.com/jekyll/jekyll-redirect-from) which works well but requires running `gem install jekyll-redirect-from` once for local development builds.

As the whole thing is highly nit-picky, there are no hard feelings if you decide not to merge.

### CODE REVIEW

**Comment by Samwise007** [comment]
Hi Philipp,

thanks for all the work! I couldn't automatically merge, but I altered
the files as you suggested.

Thanks!
Felix

Am 18/05/16 um 00:00 schrieb Philipp Bock:

**Comment by Samwise007** [comment]
Hi Philipp,

I'm getting a build-error (
You have an error on line 5 of your `_config.yml` file.)
I did run 'gem install jekyll-redirect-from'...
Any idea what's the problem?

**Comment by pbock** [comment]
Pretty sure it's the `+` at the start of the line causing the problem. I'm not sure what it's doing there either – I've never seen that in a YAML file.

You should probably delete the other plus signs as well, although that might have unintended side-effects as configuration options that were previously `nil` (by accident) now get defined.

**Comment by Samwise007** [comment]
Okay, that's seems to solve the problem. The only problem I found is that if you switch languages after opening a post (like http://xhain-hackspace.github.io/news/2016/04/18/hackspace-statt-Angst-Er%C3%B6ffnung-am-Freitag,-den-13.-Mai-2016.html) you'll get a 404, because the english version of the post has a different URI ( http://xhain-hackspace.github.io/en/news/2016/04/18/opening.html not http://xhain-hackspace.github.io/en/news/2016/04/18/hackspace-statt-Angst-Er%C3%B6ffnung-am-Freitag,-den-13.-Mai-2016.html).

**Comment by pbock** [comment]
Ah, I just saw, my commits were a bit confusing. I originally implemented the redirects with a custom layout file (`_layouts/redirect.html`), but then I bothered reading the documentation and saw that `jekyll-redirect-from` was the recommended solution and also leads to a neater file structure because the necessary HTML pages are generated automatically. That means we can delete `calender.html` (it will automatically be generated by `jekyll-redirect-from`) and change the metadata in `calendar.html` as follows:

``` yaml
---
lang: de
layout: main
redirect_from: calender.html
---
```

You can use the same approach to redirect the blog post, but the ideal solution would of course be to never link to the wrong URI in the first place. If you don't mind, I'll send another pull request that adds a way to overwrite the URI of translated pages.

**Comment by Samwise007** [comment]
I don't mind at all, I really appreciate your help!

**Pull request closed without merging**
